### ISSUE TITLE
Migrate codebase to Javascript

### ISSUE THREAD

**Issue by jljorgenson18** [jbrid867/MasterEquation#1]
Clearly, Python is limited and confusing. I mean which do I use? Python2 or Python3? I think the easiest way to move forward would be to migrate to Node.js and to use at least 8 babel plugins. I would also consider PHP as a viable solution since it is used by Facebook and Slack so it can't be wrong.

**Comment by johnbridstrup** [comment]
I tried to migrate to javascript, but I ended up being sent to javascript in order to get to javascript where they told me to use javascript and then javascript informed me that i was not using javascript

**Comment by johnbridstrup** [comment]
it was all just one big "note to self"
